// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSerf.Lighthouse.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NSerf.Lighthouse.Migrations
{
    [DbContext(typeof(LighthouseDbContext))]
    partial class LighthouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NSerf.Lighthouse.Data.Entities.ClusterEntity", b =>
                {
                    b.Property<Guid>("ClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.HasKey("ClusterId");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("clusters", (string)null);
                });

            modelBuilder.Entity("NSerf.Lighthouse.Data.Entities.NodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_payload");

                    b.Property<long>("ServerTimeStamp")
                        .HasColumnType("bigint")
                        .HasColumnName("server_timestamp");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("version_name");

                    b.Property<long>("VersionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "VersionName", "VersionNumber", "ServerTimeStamp")
                        .HasDatabaseName("idx_nodes_cluster_version_timestamp");

                    b.ToTable("nodes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
